Repository UNIZAR-30226-2025-07/frontend-movil, pull requests merged in 2025-05, with the labels that each got.

#43 Tienda
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/java/eina/unizar/frontend_movil/ui/functions/Functions.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/functions/FunctionsUserId.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/StoreScreen.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/utils/Color.kt
  app/src/main/res/drawable/aspecto_basico.png
  app/src/main/res/drawable/balatro.png
  app/src/main/res/drawable/baloncesto.png
  app/src/main/res/drawable/ben_ten.png
  app/src/main/res/drawable/cristiano.png
  app/src/main/res/drawable/default_skin.xml
  app/src/main/res/drawable/doraemon.png
  app/src/main/res/drawable/espagna.png
  app/src/main/res/drawable/fc_barcelona.png
  app/src/main/res/drawable/francia.png
  app/src/main/res/drawable/futbol.png
  app/src/main/res/drawable/horimiya.png
  app/src/main/res/drawable/italia.png
  app/src/main/res/drawable/javi_poves.png
  app/src/main/res/drawable/jim.png
  app/src/main/res/drawable/jupiter.png
  app/src/main/res/drawable/kaneki.png
  app/src/main/res/drawable/kaori.png
  app/src/main/res/drawable/kousei.png
  app/src/main/res/drawable/london_eye.png
  app/src/main/res/drawable/luffi.png
  app/src/main/res/drawable/luigi_bros.png
  app/src/main/res/drawable/mario_bros.png
  app/src/main/res/drawable/messi.png
  app/src/main/res/drawable/mike.png
  app/src/main/res/drawable/naranja.png
  app/src/main/res/drawable/paella.png
  app/src/main/res/drawable/pase_de_temporada.png
  app/src/main/res/drawable/pokemon.png
  app/src/main/res/drawable/portugal.png
  app/src/main/res/drawable/real_madrid.png
  app/src/main/res/drawable/real_zaragoza.png
  app/src/main/res/drawable/recio.png
  app/src/main/res/drawable/rosquilla.png
  app/src/main/res/drawable/sd_huesca.png
  app/src/main/res/drawable/simpsons.png
  app/src/main/res/drawable/sol.png
  app/src/main/res/drawable/tenis.png
  app/src/main/res/drawable/tierra.png
  app/src/main/res/drawable/tierra_plana.png
  app/src/main/res/drawable/unizar.png
  app/src/main/res/drawable/voleyball.png
  app/src/main/res/drawable/zelda.png
  gradle/libs.versions.toml
Labels: conexion-backend

#44 Modificado lo necesario para que la pantalla de amigos sea completamente funcional.
  .idea/caches/deviceStreaming.xml
  .idea/deploymentTargetSelector.xml
  .idea/misc.xml
  app/src/main/java/eina/unizar/frontend_movil/ui/functions/Functions.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/AddFriendScreen.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/FriendRequestsScreen.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/FriendsScreen.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/MainMenuScreen.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/theme/Color.kt
Labels: conexion-backend

#45 Privates2
  app/src/main/java/eina/unizar/frontend_movil/ui/models/Player.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/GameTypeSelectionScreen.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/JoinPrivateRoomScreen.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/PrivateRoomScreen.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/WaitingRoomScreen.kt
  gradle/libs.versions.toml
Labels: conexion-backend

#46 Integrar pantalla de logros
  app/src/main/java/eina/unizar/frontend_movil/ui/navigation/AppNavigation.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/AchievementsScreen.kt
Labels: conexion-backend

#47 Seleccionador de aspectos y minor fixes
  app/src/main/java/eina/unizar/frontend_movil/ui/components/AspectSelector.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/navigation/AppNavigation.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/MainMenuScreen.kt
Labels: bug, enhancement

#54 Pase de temporada en el móvil
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/BattlePassScreen.kt
  app/src/main/res/drawable/ic_coins.xml
  app/src/main/res/drawable/ic_gems.xml
  app/src/main/res/drawable/ic_lock.xml
  app/src/main/res/drawable/ic_premium_reward_placeholder.xml
  app/src/main/res/drawable/ic_reward_placeholder.xml
  app/src/main/res/drawable/ic_skin.xml
  app/src/main/res/drawable/level_circle.xml
  app/src/main/res/drawable/level_completed_background.xml
  app/src/main/res/drawable/level_current_background.xml
  app/src/main/res/drawable/level_locked_background.xml
  app/src/main/res/drawable/premium_reward_background.xml
  app/src/main/res/drawable/progress_bar_background.xml
  app/src/main/res/drawable/progress_bar_fill.xml
  app/src/main/res/drawable/reward_background.xml
  app/src/main/res/layout/fragment_battle_pass.xml
  app/src/main/res/layout/item_battle_pass_level.xml
  app/src/main/res/values/colors.xml
  gradle/libs.versions.toml
Labels: conexion-backend

#55 Componente Pase de Batalla en menú inicial
  app/src/main/java/eina/unizar/frontend_movil/ui/components/BattlePass.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/navigation/AppNavigation.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/MainMenuScreen.kt
Labels: enhancement

#60 Pantalla para la comunicación del soporte
  app/src/main/java/eina/unizar/frontend_movil/ui/navigation/AppNavigation.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/SettingsScreen.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/SupportScreen.kt
Labels: enhancement

#61 Arreglar contact-support
  app/src/main/java/eina/unizar/frontend_movil/ui/components/AspectSelector.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/AchievementsScreen.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/MainMenuScreen.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/SupportScreen.kt
Labels: bug

#63 Bug fix, música continuaba sonando en reposo
  app/src/main/java/eina/unizar/frontend_movil/MainActivity.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/utils/MusicManager.kt
Labels: bug

#66 Bugs fixed
  app/src/main/java/eina/unizar/frontend_movil/ui/components/AspectSelector.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/ForgotPasswordScreen.kt
  app/src/main/java/eina/unizar/frontend_movil/ui/screens/MainMenuScreen.kt
Labels: bug
